# Site settings
title: Piráti.cz
description: > # this means to ignore newlines until "baseurl:"
  Evropa je naše moře! S tímto heslem vstupuje Česká pirátská strana 
  do Evropských parlamentních voleb, kde bude prosazovat základní pirátské myšlenky.
keywords: piráti,evropa,volby 2014,evropský parlament,kandidáti,Ivan Bartoš,Marcel Kolaja,Markéta Gregorová,Vojtěch Pikal,Tomáš Tožička,Česká pirátská strana
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://volimpiraty.cz" # the base hostname & protocol for your site
ga: UA-46899507-7
twitter: PiratePartyCZ
facebook: ceska.piratska.strana
youtube: CeskaPiratskaStrana

permalink:     :title.html

# Build settings
markdown: kramdown
