# Site settings
title: Piráti a Zdravé Letňany / Komunální volby 2014
description: > # this means to ignore newlines until "baseurl:"
  Evropa je naše moře! S tímto heslem vstupuje Česká pirátská strana 
  do Evropských parlamentních voleb, kde bude prosazovat základní pirátské myšlenky.
keywords: piráti,komunální volby,volby 2014,kandidáti,Olaf Deutsch,Vladislav Tobias Esner,Jaroslava Šebková,Ivan Polák,Česká pirátská strana,Zdravé Letňany
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://praha18.pirati.cz" # the base hostname & protocol for your site
twitter: PiratePartyCZ
facebook: ceska.piratska.strana
youtube: CeskaPiratskaStrana

# Build settings
markdown: kramdown

# candidates
candidates:
    deutsch:
        fullname: Olaf Deutsch
        name: Olaf Deutsch
        sub: předseda Zdravé Letňany o.s.
        image: deutsch-th.jpg
        image_big: deutsch.jpg
        page: olaf-deutsch.html
    esner:
        fullname: Vladislav Tobias Esner
        name: Vladislav Tobias Esner
        sub: Kandidát číslo 2
        image: esner-th.jpg
        image_big: esner.jpg
        page: tobias-esner.html
    sebkova:
        fullname: Jaroslava Šebková
        name: Jaroslava Šebková
        sub: Kandidát číslo 3
        image: sebkova-th.jpg
        image_big: sebkova.jpg
        page: jaroslava-sebkova.html
    polak:
        fullname: Ivan Polák
        name: Ivan Polák
        sub: Kandidát číslo 4
        image: polak-th.jpg
        image_big: polak.jpg
        page: ivan-polak.html
